version: '3.7' 
services: 
  shop: 
    build: . 
    ports: 
      - '80:80'
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=oxid
      - MYSQL_USER=oxid
      - MYSQL_PASSWORD=oxid
      - OXID_EDITION=ce
      - SHOP_URL=http://localhost
  db:
    image: mariadb
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=oxid
      - MYSQL_DATABASE=oxid
      - MYSQL_USER=oxid
      - MYSQL_PASSWORD=oxid