modules:
  osc-unzer:
    moduleSettings:
      sandbox-UnzerPublicKey:
        group: unzermerchant
        type: str
        value: SANDBOXUNZERPUBLICKEY
      sandbox-UnzerPrivateKey:
        group: unzermerchant
        type: str
        value: SANDBOXUNZERRPRIVATEKEY
      sandbox-applepay_merchant_identifier:
        group: unzerapplepay
        type: str
        value: APPLEPAYMERCHANTIDENTIFIER
      applepay_label:
        group: unzerapplepay
        type: str
        value: APPLEPAYLABEL
      sandboxApplePayPaymentKeyId:
        type: str
        value: s-key-13
      sandboxApplePayPaymentCertificateId:
        type: str
        value: s-crt-6
      registeredWebhookId:
        type: str
        value: s-whk-100023329
