[{assign var="payment" value=$oView->getPayment()}]
[{if $payment->getId() === 'oscunzer_applepay'}]
    [{include file="@osc-unzer/frontend/tpl/order/applepay_button"}]
[{else}]
    [{$smarty.block.parent}]
[{/if}]