<?php

/**
 * Copyright © OXID eSales AG. All rights reserved.
 * See LICENSE file for license details.
 */

$sLangName = "Deutsch";

$aLang = [
    "charset" => "UTF-8",
    'SHOP_MODULE_GROUP_unzermerchant' => 'Zugangsdaten',
    'SHOP_MODULE_GROUP_unzerenvironment' => 'Betriebsmodus',
    'SHOP_MODULE_GROUP_unzercard' => 'zusätzliche Optionen für Kreditkarten',
    'SHOP_MODULE_GROUP_unzerpaypal' => 'zusätzliche Optionen für PayPal',
    'SHOP_MODULE_GROUP_unzerapplepay' => 'zusätzliche Optionen für ApplePay',
    'SHOP_MODULE_GROUP_unzerinstallment' => 'zusätzliche Optionen für Ratenzahlung',
    'SHOP_MODULE_GROUP_unzerother' => 'Sonstiges',
    'SHOP_MODULE_sandbox-UnzerPublicKey' => 'Sandbox Public-Key',
    'SHOP_MODULE_sandbox-UnzerPrivateKey' => 'Sandbox Private-Key',
    'SHOP_MODULE_production-UnzerPublicKey' => 'Production Public-Key',
    'SHOP_MODULE_production-UnzerPrivateKey' => 'Production Private-Key',
    'SHOP_MODULE_UnzerSystemMode' => 'Modus',
    'SHOP_MODULE_UnzerSystemMode_0' => 'Sandbox',
    'SHOP_MODULE_UnzerSystemMode_1' => 'Livebetrieb',
    'SHOP_MODULE_UnzerOption_oscunzer_card' => 'Kreditkarte',
    'SHOP_MODULE_UnzerOption_oscunzer_card_0' => 'direct Capture',
    'SHOP_MODULE_UnzerOption_oscunzer_card_1' => 'Authorize & later Capture',
    'SHOP_MODULE_UnzerOption_oscunzer_paypal' => 'Paypal',
    'SHOP_MODULE_UnzerOption_oscunzer_paypal_0' => 'direct Capture',
    'SHOP_MODULE_UnzerOption_oscunzer_paypal_1' => 'Authorize & later Capture',
    'SHOP_MODULE_UnzerOption_oscunzer_applepay' => 'Apple Pay',
    'SHOP_MODULE_UnzerOption_oscunzer_applepay_0' => 'direct Capture',
    'SHOP_MODULE_UnzerOption_oscunzer_applepay_1' => 'Authorize & later Capture',
    'SHOP_MODULE_UnzerOption_oscunzer_installment_rate' => 'Zinssatz für Ratenzahlung',
    'HELP_SHOP_MODULE_UnzerOption_oscunzer_installment_rate' => 'Zinssatz in %, Dezimaltrennzeichen "." z.B.: "4.5"',
    'SHOP_MODULE_UnzerjQuery' => 'Einbindung von jQuery über das Modul',
    'HELP_SHOP_MODULE_UnzerSystemMode' => 'Wechseln Sie hier zwischen Sandbox (Testmodus) und Livebetrieb',
    'SHOP_MODULE_UnzerDebug' => 'Debug-Modus aktivieren',
    'HELP_SHOP_MODULE_UnzerDebug' => 'Im aktiven Debug-Modus werden Log-Files in das Verzeichnis /log/unzer geschrieben.',
    'HELP_SHOP_MODULE_UnzerLogLevel' => 'Das Log Level bestimmt, welche Ereignisse in der Logdatei protokolliert werden. Mögliche Werte
     sind Debug (alles), Warning (Warnungen und Fehler), oder Error (nur Fehler).',
    'SHOP_MODULE_WEBHOOK' => 'Registrierter Webhook',
    'SHOP_MODULE_REGISTER_WEBHOOK' => 'Webhook für diesen Shop registrieren',
    'SHOP_MODULE_DELETE_WEBHOOK' => 'Webhook für diesen Shop löschen',
    'SHOP_MODULE_WEBHOOK_NO_UNZER' => 'Um ein Webhook registrieren zu können, müssen die Unzer-Keys hinterlegt sein.',
    'SHOP_MODULE_APPLE_PAY_PAYMENT_CERTS_PROCESSED' => 'Zahlungs-Zertifikate wurden übertragen',
    'SHOP_MODULE_TRANSFER_APPLE_PAY_PAYMENT_DATA' => 'Zahlungs-Zertifikate übertragen',
    'SHOP_MODULE_RETRANSFER_APPLE_PAY_PAYMENT_DATA' => 'Neue Zahlungs-Zertifikate übertragen',
    'SHOP_MODULE_APPLE_PAY_PAYMENT_PROCESSING_CERT' => 'Zertifikat zur Zahlungsabwicklung',
    'SHOP_MODULE_APPLE_PAY_PAYMENT_PROCESSING_CERT_KEY' => 'Privater Key zur Zahlungsabwicklung',
    'SHOP_MODULE_applepay_merchant_identifier' => 'Merchant Identifier',
    'SHOP_MODULE_applepay_merchant_cert' => 'Merchant Zertifikat',
    'SHOP_MODULE_applepay_merchant_cert_key' => 'Merchant Zertifikat Private Key',
    'SHOP_MODULE_TRANSFER_APPLE_PAY_CERT' => 'Zertifikat an Unzer übertragen',
    'SHOP_MODULE_TRANSFER_APPLE_PAY_PRIVATE_KEY' => 'Key an Unzer übertragen',
    'SHOP_MODULE_applepay_merchant_capabilities' => 'Unterstützte Zahlungsarten',
    'SHOP_MODULE_applepay_merchant_capabilities_supportsCredit' => 'Kreditkarte',
    'HELP_SHOP_MODULE_applepay_merchant_capabilities' => 'Vom Händler unterstütze Zahlungsarten. Der Wert "supports3DS" wird immer an Apple Pay gesendet. Der Rest ist optional.',
    'SHOP_MODULE_applepay_merchant_capabilities_supportsDebit' => 'Debitkarte',
    'SHOP_MODULE_applepay_merchant_capabilities_supportsEMV' => 'China Union Pay Transaktionen',
    'SHOP_MODULE_applepay_networks' => 'Unterstütze Kreditkarten',
    'HELP_SHOP_MODULE_applepay_networks' => 'Vom Händler unterstützte Kreditkarten. Wenn Kreditkarte unterstützt wird, müssen Sie zumindest eine der Kreditkartenarten anwählen.',
    'SHOP_MODULE_applepay_networks_amex' => 'American Express',
    'SHOP_MODULE_applepay_networks_cartesBancaires' => 'Cartes Bancaires',
    'SHOP_MODULE_applepay_networks_chinaUnionPay' => 'China Union Pay',
    'SHOP_MODULE_applepay_networks_discover' => 'Discover',
    'SHOP_MODULE_applepay_networks_eftpos' => 'EFTPOS',
    'SHOP_MODULE_applepay_networks_electron' => 'Visa Electron',
    'SHOP_MODULE_applepay_networks_elo' => 'Elo',
    'SHOP_MODULE_applepay_networks_interac' => 'Interac',
    'SHOP_MODULE_applepay_networks_jcb' => 'JCB',
    'SHOP_MODULE_applepay_networks_mada' => 'Mada',
    'SHOP_MODULE_applepay_networks_maestro' => 'Maestro',
    'SHOP_MODULE_applepay_networks_masterCard' => 'Mastercard',
    'SHOP_MODULE_applepay_networks_privateLabel' => 'Private Label',
    'SHOP_MODULE_applepay_networks_visa' => 'Visa',
    'SHOP_MODULE_applepay_networks_vPay' => 'V-Pay',
    'SHOP_MODULE_applepay_label' => 'Firma',
    'HELP_SHOP_MODULE_applepay_label' => 'Wenn kein Wert eingetragen ist, wird stattdessen der in den Grundeinstellungen hinterlegte Firmenname verwendet',
];
