[{assign var="payment" value=$oView->getPayment()}]
[{if $oViewConf->checkUnzerHealth() && $payment->isUnzerPayment()}]
    [{include file="modules/osc/unzer/unzer_shippingAndPayment_flow.tpl"}]
[{else}]
    [{$smarty.block.parent}]
[{/if}]