[{assign var="payment" value=$oView->getPayment()}]

[{if $payment->isUnzerPayment()}]
    [{if $oViewConf->isFlowCompatibleTheme()}]
        [{include file="modules/osc/unzer/unzer_shippingAndPayment_flow.tpl"}]
    [{else}]
        [{include file="modules/osc/unzer/unzer_shippingAndPayment_wave.tpl"}]
    [{/if}]
[{else}]
    [{$smarty.block.parent}]
[{/if}]