<?php

/**
 * Copyright © OXID eSales AG. All rights reserved.
 * See LICENSE file for license details.
 */

$sLangName = "English";

$aLang = [
    "charset" => "UTF-8",
    'SHOP_MODULE_GROUP_unzermerchant' => 'Access Data',
    'SHOP_MODULE_GROUP_unzerenvironment' => 'Operation mode',
    'SHOP_MODULE_GROUP_unzercard' => 'additional options for credit cards',
    'SHOP_MODULE_GROUP_unzerpaypal' => 'additional options for PayPal',
    'SHOP_MODULE_GROUP_unzerapplepay' => 'additional options for ApplePay',
    'SHOP_MODULE_GROUP_unzerinstallment' => 'additional options for Installment',
    'SHOP_MODULE_GROUP_unzerother' => 'Other',
    'SHOP_MODULE_sandbox-UnzerPublicKey' => 'Sandbox Public-Key',
    'SHOP_MODULE_sandbox-UnzerPrivateKey' => 'Sandbox Private-Key',
    'SHOP_MODULE_production-UnzerPublicKey' => 'Production Public-Key',
    'SHOP_MODULE_production-UnzerPrivateKey' => 'Production Private-Key',
    'SHOP_MODULE_UnzerSystemMode' => 'Mode',
    'SHOP_MODULE_UnzerSystemMode_0' => 'Sandbox',
    'SHOP_MODULE_UnzerSystemMode_1' => 'Production',
    'SHOP_MODULE_UnzerOption_oscunzer_card' => 'CreditCard',
    'SHOP_MODULE_UnzerOption_oscunzer_card_0' => 'direct Capture',
    'SHOP_MODULE_UnzerOption_oscunzer_card_1' => 'Authorize & later Capture',
    'SHOP_MODULE_UnzerOption_oscunzer_paypal' => 'PayPal',
    'SHOP_MODULE_UnzerOption_oscunzer_paypal_0' => 'direct Capture',
    'SHOP_MODULE_UnzerOption_oscunzer_paypal_1' => 'Authorize & later Capture',
    'SHOP_MODULE_UnzerOption_oscunzer_applepay' => 'Apple Pay',
    'SHOP_MODULE_UnzerOption_oscunzer_applepay_0' => 'direct Capture',
    'SHOP_MODULE_UnzerOption_oscunzer_applepay_1' => 'Authorize & later Capture',
    'SHOP_MODULE_UnzerOption_oscunzer_installment_rate' => 'Installment rate',
    'HELP_SHOP_MODULE_UnzerOption_oscunzer_installment_rate' => 'Installmentrate per 100 in %, i.e.: "4.5"',
    'SHOP_MODULE_UnzerjQuery' => 'Include jQuery via the module',
    'HELP_SHOP_MODULE_UnzerSystemMode' => 'Here you can switch between Sandbox (demo mode) and Production mode',
    'SHOP_MODULE_UnzerDebug' => 'Enable debug mode',
    'HELP_SHOP_MODULE_UnzerDebug' => 'In active debug mode, log files are written to the /log/unzer directory.',
    'HELP_SHOP_MODULE_UnzerLogLevel' => 'The log level determines which events are logged in the log file.
        Possible values are Debug (all), Warning (warnings and errors), or Error (only errors).',
    'SHOP_MODULE_WEBHOOK' => 'Registered Webhook',
    'SHOP_MODULE_REGISTER_WEBHOOK' => 'Register Webhook',
    'SHOP_MODULE_DELETE_WEBHOOK' => 'Delete Webhook',
    'SHOP_MODULE_WEBHOOK_NO_UNZER' => 'In order to register a webhook, the Unzer keys must be stored',
    'SHOP_MODULE_APPLE_PAY_PAYMENT_CERTS_PROCESSED' => 'Payment certificates have been transferred',
    'SHOP_MODULE_TRANSFER_APPLE_PAY_PAYMENT_DATA' => 'transfer Payment certificates',
    'SHOP_MODULE_RETRANSFER_APPLE_PAY_PAYMENT_DATA' => 'Transfer new payment certificates ',
    'SHOP_MODULE_APPLE_PAY_PAYMENT_PROCESSING_CERT' => 'Payment Processing Certificate ',
    'SHOP_MODULE_APPLE_PAY_PAYMENT_PROCESSING_CERT_KEY' => 'Private key for payment processing ',
    'SHOP_MODULE_applepay_merchant_identifier' => 'Merchant Identifier',
    'SHOP_MODULE_applepay_merchant_cert' => 'Merchant Certificate',
    'SHOP_MODULE_applepay_merchant_cert_key' => 'Merchant Certificate Private Key',
    'SHOP_MODULE_TRANSFER_APPLE_PAY_CERT' => 'Transfer certificate to unzer',
    'SHOP_MODULE_TRANSFER_APPLE_PAY_PRIVATE_KEY' => 'Transfer key to unzer',
    'SHOP_MODULE_applepay_merchant_capabilities' => 'Supported payment types',
    'SHOP_MODULE_applepay_merchant_capabilities_supportsCredit' => 'Credit Card',
    'HELP_SHOP_MODULE_applepay_merchant_capabilities' => 'Payment methods supported by the merchant. The value "supports3DS" is always sent to Apple Pay. The rest is optional.',
    'SHOP_MODULE_applepay_merchant_capabilities_supportsDebit' => 'Debit Card',
    'SHOP_MODULE_applepay_merchant_capabilities_supportsEMV' => 'China Union Pay transactions',
    'SHOP_MODULE_applepay_networks' => 'Supported credit cards',
    'HELP_SHOP_MODULE_applepay_networks' => 'Credit cards supported by the merchant. If credit card is supported, you must select at least one of the credit card types',
    'SHOP_MODULE_applepay_networks_amex' => 'American Express',
    'SHOP_MODULE_applepay_networks_cartesBancaires' => 'Cartes Bancaires',
    'SHOP_MODULE_applepay_networks_chinaUnionPay' => 'China Union Pay',
    'SHOP_MODULE_applepay_networks_discover' => 'Discover',
    'SHOP_MODULE_applepay_networks_eftpos' => 'EFTPOS',
    'SHOP_MODULE_applepay_networks_electron' => 'Visa Electron',
    'SHOP_MODULE_applepay_networks_elo' => 'Elo',
    'SHOP_MODULE_applepay_networks_interac' => 'Interac',
    'SHOP_MODULE_applepay_networks_jcb' => 'JCB',
    'SHOP_MODULE_applepay_networks_mada' => 'Mada',
    'SHOP_MODULE_applepay_networks_maestro' => 'Maestro',
    'SHOP_MODULE_applepay_networks_masterCard' => 'Mastercard',
    'SHOP_MODULE_applepay_networks_privateLabel' => 'Private Label',
    'SHOP_MODULE_applepay_networks_visa' => 'Visa',
    'SHOP_MODULE_applepay_networks_vPay' => 'V-Pay',
    'SHOP_MODULE_applepay_label' => 'Company',
    'HELP_SHOP_MODULE_applepay_label' => 'If no value is entered, the company name stored in the basic settings is used instead',
];