[{assign var="payment" value=$oView->getPayment()}]
[{assign var="sPaymentID" value=$payment->getId()}]

[{if $sPaymentID == "oscunzer_banktransfer"}]
    [{include file="modules/osc/unzer/unzer_banktransfer.tpl"}]
    [{elseif $sPaymentID == "oscunzer_card"}]
    [{include file="modules/osc/unzer/unzer_card.tpl"}]
    [{elseif $sPaymentID == "oscunzer_eps"}]
    [{include file="modules/osc/unzer/unzer_eps_charge.tpl"}]
    [{elseif $sPaymentID == "oscunzer_giropay"}]
    [{include file="modules/osc/unzer/unzer_giro.tpl"}]
    [{elseif $sPaymentID == "oscunzer_ideal"}]
    [{include file="modules/osc/unzer/unzer_ideal.tpl"}]
    [{elseif $sPaymentID == "oscunzer_installment"}]
    [{include file="modules/osc/unzer/installment.tpl"}]
    [{elseif $sPaymentID == "oscunzer_invoice"}]
    [{include file="modules/osc/unzer/unzer_invoice.tpl"}]
    [{elseif $sPaymentID == "oscunzer_invoice-secured"}]
    [{include file="modules/osc/unzer/unzer_invoice_securred.tpl"}]
    [{elseif $sPaymentID == "oscunzer_paypal"}]
    [{include file="modules/osc/unzer/unzer_paypal.tpl"}]
    [{elseif $sPaymentID == "oscunzer_post-finance"}]
    [{include file="modules/osc/unzer/unzer_invoice.tpl"}]
    [{elseif $sPaymentID == "oscunzer_prepayment"}]
    [{include file="modules/osc/unzer/unzer_prepayment.tpl"}]
    [{elseif $sPaymentID == "oscunzer_sepa"}]
    [{include file="modules/osc/unzer/unzer_sepa.tpl"}]
    [{elseif $sPaymentID == "oscunzer_sepa-secured"}]
    [{include file="modules/osc/unzer/unzer_sepa.tpl"}]
    [{elseif $sPaymentID == "oscunzer_sofort"}]
    [{include file="modules/osc/unzer/unzer_sofort.tpl"}]
    [{else}]
    [{$smarty.block.parent}]
    [{/if}]
