name: Remove old artifacts

on:
  schedule:
    # Every day at 1am
    - cron: '0 8 * * *'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Delete workflow runs
      uses: dmvict/clean-workflow-runs@v1.0.0
      with:
        save_period: 5
        save_min_runs_number: 5
        dry: false

#    - name: Remove old artifacts
#      uses: c-hive/gha-remove-artifacts@v1
#      with:
#        age: '1 day'
        # Optional inputs
        # skip-tags: true
#        skip-recent: 2
