name: oxid module tests

on: [push]

jobs:
  install:
    strategy:
      matrix:
        php: [ 7.4 ]
        oxid: [ 6.3 ]
    runs-on: ubuntu-latest
    container:
      image: oxidprojects/oxid-apache-php:oxid${{ matrix.oxid }}-php${{ matrix.php }}
      options: --tmpfs=/build:noatime
    env:
      MODULE_NAME: oxid-solution-catalysts/unzer
      MYSQL_DATABASE: oxid
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      SHOP_URL: http://localhost/      
    steps:
      - uses: actions/checkout@v2

      - name: install
        run: composer create-project oxid-professional-services/test-oxid /build/oxid dev-oxid${{matrix.oxid}} --no-interaction -s dev --repository="{\"url\":\"https://github.com/keywan-ghadami-oxid/test-oxid.git\", \"type\":\"vcs\"}" --remove-vcs 

      - name: move artifacts to projects folder
        run: |
          mkdir -p /build/oxid/project-modules/module-under-test && cp -r * /build/oxid/project-modules/module-under-test
      - name: add project module folder
        run:
          composer config repositories.build path /build/oxid/project-modules/\*
        working-directory: /build/oxid

      - name: require module
        run: composer require --no-interaction $MODULE_NAME
        working-directory: /build/oxid

      - name: move config to source folder
        run: cp config.inc.php-dist source/config.inc.php
        working-directory: /build/oxid

      - name: prepare autoload
        run: composer update
        working-directory: /build/oxid/vendor/oxid-solution-catalysts/unzer/

      - name: run phpcs
        continue-on-error: true
        id: phpcs
        run: php vendor/bin/phpcs --standard=Tests/phpcs.xml
        working-directory: /build/oxid/vendor/oxid-solution-catalysts/unzer/

      - name: run psalm
        continue-on-error: true
        id: psalm
        run: php vendor/bin/psalm --show-info=true --no-cache --report=logs/psalm.sonarqube.json
        working-directory: /build/oxid/vendor/oxid-solution-catalysts/unzer/

      - name: Save psalm logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          retention-days: 30
          name: psalm-log
          path: /build/oxid/vendor/oxid-solution-catalysts/unzer/logs/psalm.sonarqube.json
      - name: mysql shema
        run: mysql -u $MYSQL_USER -h db -p$MYSQL_PASSWORD $MYSQL_DATABASE < "vendor/oxid-esales/oxideshop-ce/source/Setup/Sql/database_schema.sql"
        working-directory: /build/oxid

      - name: mysql data
        run: mysql -u $MYSQL_USER -h db -p$MYSQL_PASSWORD $MYSQL_DATABASE < "vendor/oxid-esales/oxideshop-ce/source/Setup/Sql/initial_data.sql"
        working-directory: /build/oxid

      - name: console install-configuration
        run: vendor/bin/oe-console oe:module:install-configuration source/modules/osc/unzer/
        working-directory: /build/oxid

      - name: console apply-configuration
        run: vendor/bin/oe-console oe:module:apply-configuration
        working-directory: /build/oxid

      - name: console db migrations
        run: vendor/bin/oe-eshop-db_migrate migrations:migrate
        working-directory: /build/oxid

      - name: console generate views
        run: vendor/bin/oe-eshop-db_views_generate
        working-directory: /build/oxid

      - name: console activate module
        run: vendor/bin/oe-console oe:module:activate osc-unzer
        working-directory: /build/oxid

      - name: check mod config
        run: cat var/configuration/shops/1.yaml
        working-directory: /build/oxid

      - name: composer validate
        run: composer validate
        working-directory: /build/oxid

      - name: oxid config
        run: cat source/config.inc.php
        working-directory: /build/oxid

      - name: run unit tests
        run: |
          XDEBUG_MODE=coverage php vendor/bin/phpunit \
            --bootstrap vendor/oxid-esales/testing-library/bootstrap.php \
            -c /build/oxid/vendor/oxid-solution-catalysts/unzer/Tests/phpunit.xml \
            --coverage-clover=/build/oxid/logs/clover.xml \
            --coverage-text \
            --log-junit /build/oxid/logs/phpunit.xml
        working-directory: /build/oxid

      - name: Save logs
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: /build/oxid/logs
          retention-days: 1
      - name: fail on psalm error
        if: steps.psalm.outcome != 'success' || steps.phpcs.outcome != 'success'
        run: exit 1 
    services:
      db:
        image: mariadb:10.5
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: oxid
        ports:
          - 3306
        options: --tmpfs=/tmp:noatime --tmpfs=/var/lib/mysql:noatime --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

  sonarcloud:
    needs: [install]
    runs-on: ubuntu-latest
    if: always() && (needs.oxid_unit_tests.result != 'failure')
    steps:
      - name: Checkout module
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: List
        run: |
          pwd
          ls -alh

      - name: Load phpunit logs
        uses: actions/download-artifact@v2
        with:
          name: logs
          path: logs

      - name: Load psalm logs
        uses: actions/download-artifact@v2
        with:
          name: psalm-log
          path: logs/

      - name: Fix phpunit logs
        run: |
          ls -alh logs
          sed -i 's+/build/oxid/project-modules/module-under-test/++gI' logs/clover.xml
          sed -i 's+/build/oxid/project-modules/module-under-test/++gI' logs/phpunit.xml

      - name: Save logs
        uses: actions/upload-artifact@v2
        with:
          name: logs-adjusted
          path: logs
          retention-days: 1

      - name: Show logs
        run: |
          ls -alh logs
          cat logs/clover.xml
          cat logs/phpunit.xml
          cat logs/psalm.sonarqube.json

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=oxid-esales
            -Dsonar.projectKey=OXID-eSales_unzer-module
            -Dsonar.projectVersion=0.1.0
            -Dsonar.sources=src
            -Dsonar.tests=Tests
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.php.coverage.reportPaths=logs/clover.xml
            -Dsonar.php.tests.reportPath=logs/phpunit.xml
            -Dsonar.php.psalm.reportPaths=logs/psalm.sonarqube.json
            -Dsonar.cpd.php.minimumTokens=30
            -Dsonar.cpd.php.minimumLines=6
