name: Trigger

on:
  pull_request:
  push:
  schedule:
    - cron: '0 6 * * 1-5'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  p81m80both:
    name: 'Php-8.1-Mysql-8.0'
    uses: ./.github/workflows/development.yml
    secrets: inherit
    with:
      php: '8.1'
      mysql: '8.0'
